### ISSUE TITLE
Review: readme, intro-1 and intro-2

### ISSUE THREAD

**Issue by 3v0k4** [AkkarinForest/Haskell-Workshop#5]
Check only if you think this is good to go. Otherwise, comment with suggestions.

- [x] @AkkarinForest 
- [x] @3v0k4

**Comment by alex-suminski** [comment]
Intro 2 
`Fill the ... using the prefixed plus operator (ie (+))`
links to the anchor that doesn't exist. Perhaps you meant `/intro-1#partial-application`?

**Comment by alex-suminski** [comment]
Intro 2 
in `Fill the .... parse2 uses the last 3 elements of the list.` perhaps you meant last **5** elements?

**Comment by 3v0k4** [comment]
@AkkarinForest fixed both, feel free to commit yourself the fixes when they are clear mistakes 😉

**Comment by 3v0k4** [comment]
Good to go for me, waiting for your green light to open the doodle.

**Comment by alex-suminski** [comment]
good to go 🎉

**Comment by 3v0k4** [comment]
Cool, I'm gonna doodle. I'll close that at Tuesday midday and let you know then what slot was the most voted out of:

- Wednesday 16:00–17:00
- Wednesday 17:00–18:00
- Thursday 16:00–17:00
- Thursday 17:00–18:00

Great job!!
